### ISSUE TITLE
Fix storybook "oneOf" in "@storybook/addon-info" help

### ISSUE THREAD

**Issue by ldabiralai** [EurosportDigital/web-toolkit#7]
We specify "oneOf" on the button, `@storybook/addon-info` _should_ display each of the options in the UI but it does not. It'd be useful to fix this.

![image](https://user-images.githubusercontent.com/1711610/47227635-9d8ac180-d3c3-11e8-810f-210bbfb3e7c4.png)

**Comment by val3ntin** [comment]
it's a known issue which is caused by `react-docgen`
herein is more details on how to overcome it:
https://github.com/styled-components/styled-components/issues/2092
